apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-test
  description: a test component
  labels:
    business-vertical: facilities
  annotations:
    release-version: 1.0.1
    ci-cd-thingy: something
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: sandbox
  owner: team_a
  system: public-websites
---
apiVersion: backstage.io/v1alpha1
kind: user
metadata:
  name:  david.holst
spec:
  profile:
    displayName: David Holst


